/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package flitesharp;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        FLiteSharp classUnderTest = new FLiteSharp();
        //assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
